/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package phonebook;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.DefaultListModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;


/**
 *
 * @author user
 */
public class MainF extends javax.swing.JFrame implements CRUD_Interface{
    public DefaultListModel model = new DefaultListModel<>();
    /**
     * Creates new form MainF
     */
    public MainF() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AddEntryDialog = new javax.swing.JDialog();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        LastNameInput = new javax.swing.JTextField();
        FirstNameInput = new javax.swing.JTextField();
        BirthDayInput = new javax.swing.JTextField();
        NumberInput = new javax.swing.JTextField();
        EmailInput = new javax.swing.JTextField();
        AddressInput = new javax.swing.JTextField();
        SubmitButton = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        AddEntryBackButton = new javax.swing.JButton();
        BirthMonthInput = new javax.swing.JTextField();
        BirthYearInput = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        UpdateEntryDialog = new javax.swing.JDialog();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        LastNameTextField = new javax.swing.JTextField();
        FirstNameTextField = new javax.swing.JTextField();
        BirthDayTextField = new javax.swing.JTextField();
        NumberTextField = new javax.swing.JTextField();
        EmailTextField = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        AddressTextField = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        UpdateButton = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        BirthMonthTextField = new javax.swing.JTextField();
        BirthYearTextField = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>(model);
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        LastNameOutput = new javax.swing.JLabel();
        FirstNameOutput = new javax.swing.JLabel();
        BirthdayOutput = new javax.swing.JLabel();
        NumberOutput = new javax.swing.JLabel();
        AddressOutput = new javax.swing.JLabel();
        EmailOutput = new javax.swing.JLabel();
        AddEntry = new javax.swing.JButton();
        title = new javax.swing.JLabel();
        UpdateEntry = new javax.swing.JButton();
        DeleteEntry = new javax.swing.JButton();

        AddEntryDialog.setMinimumSize(new java.awt.Dimension(270, 265));

        jLabel7.setText("First Name:");

        jLabel8.setText("Last Name:");

        jLabel9.setText("Birthday:");

        jLabel10.setText("Number:");

        jLabel11.setText("Address:");

        jLabel12.setText("Email:");

        LastNameInput.setToolTipText("");
        LastNameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LastNameInputActionPerformed(evt);
            }
        });

        BirthDayInput.setText("dd");
        BirthDayInput.setToolTipText("");
        BirthDayInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BirthDayInputActionPerformed(evt);
            }
        });
        BirthDayInput.addKeyListener(new KeyAdapter(){
            @Override
            public void keyPressed(KeyEvent ke){
                keyStrokeValidate(ke,BirthDayInput,2);
            }
        });

        SubmitButton.setText("Submit");
        SubmitButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButtonActionPerformed(evt);
            }
        });

        jLabel13.setText("Input New Entry");

        AddEntryBackButton.setText("Back");
        AddEntryBackButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        AddEntryBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddEntryBackButtonActionPerformed(evt);
            }
        });

        BirthMonthInput.setText("mm");
        BirthMonthInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BirthMonthInputActionPerformed(evt);
            }
        });
        BirthMonthInput.addKeyListener(new KeyAdapter(){
            @Override
            public void keyPressed(KeyEvent ke){
                keyStrokeValidate(ke,BirthMonthInput,2);
            }
        });

        BirthYearInput.setText("yyyy");
        BirthYearInput.setToolTipText("");
        BirthYearInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BirthYearInputActionPerformed(evt);
            }
        });
        BirthYearInput.addKeyListener(new KeyAdapter(){
            @Override
            public void keyPressed(KeyEvent ke){
                keyStrokeValidate(ke,BirthYearInput,4);
            }
        });

        jLabel21.setText("/");

        jLabel22.setText("/");

        javax.swing.GroupLayout AddEntryDialogLayout = new javax.swing.GroupLayout(AddEntryDialog.getContentPane());
        AddEntryDialog.getContentPane().setLayout(AddEntryDialogLayout);
        AddEntryDialogLayout.setHorizontalGroup(
            AddEntryDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddEntryDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AddEntryDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddEntryDialogLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(FirstNameInput))
                    .addGroup(AddEntryDialogLayout.createSequentialGroup()
                        .addGroup(AddEntryDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, AddEntryDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel9)
                                .addComponent(jLabel8))
                            .addGroup(AddEntryDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel10)
                                .addGroup(AddEntryDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel11))))
                        .addGroup(AddEntryDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AddEntryDialogLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(LastNameInput))
                            .addGroup(AddEntryDialogLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(AddEntryDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(AddEntryDialogLayout.createSequentialGroup()
                                        .addComponent(AddEntryBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                                        .addComponent(SubmitButton))
                                    .addComponent(EmailInput, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(AddressInput, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(NumberInput, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(AddEntryDialogLayout.createSequentialGroup()
                                        .addComponent(BirthDayInput, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                        .addGap(4, 4, 4)
                                        .addComponent(jLabel22)
                                        .addGap(3, 3, 3)
                                        .addComponent(BirthMonthInput, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(3, 3, 3)
                                        .addComponent(jLabel21)
                                        .addGap(4, 4, 4)
                                        .addComponent(BirthYearInput, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddEntryDialogLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel13)
                        .addGap(73, 73, 73)))
                .addContainerGap())
        );
        AddEntryDialogLayout.setVerticalGroup(
            AddEntryDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddEntryDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AddEntryDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(FirstNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AddEntryDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(LastNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AddEntryDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(BirthDayInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BirthMonthInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BirthYearInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AddEntryDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NumberInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AddEntryDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(AddressInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AddEntryDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(EmailInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AddEntryDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddEntryBackButton)
                    .addComponent(SubmitButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        NumberInput.addKeyListener(new KeyAdapter(){
            @Override
            public void keyPressed(KeyEvent ke){
                keyStrokeValidate(ke,NumberInput,11);
            }
        });
        SubmitButton.addActionListener(new ActionListener(){

            @Override
            public void actionPerformed(ActionEvent e) {
                String fullDate = BirthDayInput.getText()+"/"+BirthMonthInput.getText()+"/"+BirthYearInput.getText();
                if (FirstNameInput.getText().isEmpty()||LastNameInput.getText().isEmpty()||BirthDayInput.getText().isEmpty()||AddressInput.getText().isEmpty()||EmailInput.getText().isEmpty()||NumberInput.getText().isEmpty()){

                    System.out.println("Error: Incomplete/Improper Data");
                    JOptionPane.showMessageDialog(AddEntryDialog,"Error: Incomplete/Improper","Error",JOptionPane.ERROR_MESSAGE);
                } else{
                    CRUD_Interface.addRow(FirstNameInput.getText(), LastNameInput.getText(), fullDate, AddressInput.getText(), EmailInput.getText(), NumberInput.getText());
                    int index = (model.isEmpty())? 0:indexLocate(model,convertToTitleCaseIteratingChars(FirstNameInput.getText()));
                    model.add(index, FirstNameInput.getText());
                    System.out.println(indexLocate(model,convertToTitleCaseIteratingChars(FirstNameInput.getText())));
                    AddEntryDialog.dispose();
                }
            }
        });

        UpdateEntryDialog.setMinimumSize(new java.awt.Dimension(285, 270));
        UpdateEntryDialog.setResizable(false);

        jLabel14.setText("Address:");

        jLabel15.setText("/");

        LastNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LastNameTextFieldActionPerformed(evt);
            }
        });

        FirstNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstNameTextFieldActionPerformed(evt);
            }
        });

        BirthDayTextField.setName(""); // NOI18N
        BirthDayTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BirthDayTextFieldActionPerformed(evt);
            }
        });
        BirthDayTextField.addKeyListener(new KeyAdapter(){
            @Override
            public void keyPressed(KeyEvent ke){
                keyStrokeValidate(ke,BirthDayTextField,2);
            }
        });

        NumberTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumberTextFieldActionPerformed(evt);
            }
        });

        EmailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailTextFieldActionPerformed(evt);
            }
        });

        jLabel16.setText("First Name:");

        AddressTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddressTextFieldActionPerformed(evt);
            }
        });

        jLabel17.setText("Last Name:");

        UpdateButton.setText("Update");
        UpdateButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });

        jLabel18.setText("Birthday:");

        jLabel19.setText("Update Entry");

        jLabel20.setText("Number:");

        jButton3.setText("Back");
        jButton3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        BirthMonthTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BirthMonthTextFieldActionPerformed(evt);
            }
        });

        jLabel23.setText("Email:");

        jLabel24.setText("/");

        javax.swing.GroupLayout UpdateEntryDialogLayout = new javax.swing.GroupLayout(UpdateEntryDialog.getContentPane());
        UpdateEntryDialog.getContentPane().setLayout(UpdateEntryDialogLayout);
        UpdateEntryDialogLayout.setHorizontalGroup(
            UpdateEntryDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpdateEntryDialogLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(UpdateEntryDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UpdateEntryDialogLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(UpdateEntryDialogLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(UpdateEntryDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(UpdateEntryDialogLayout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(UpdateEntryDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(NumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(UpdateEntryDialogLayout.createSequentialGroup()
                                        .addComponent(BirthDayTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(3, 3, 3)
                                        .addComponent(jLabel24)
                                        .addGap(4, 4, 4)
                                        .addComponent(BirthMonthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BirthYearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel20)
                            .addGroup(UpdateEntryDialogLayout.createSequentialGroup()
                                .addGroup(UpdateEntryDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel23))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(UpdateEntryDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, UpdateEntryDialogLayout.createSequentialGroup()
                                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(UpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(EmailTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                                    .addComponent(AddressTextField, javax.swing.GroupLayout.Alignment.LEADING)))))
                    .addGroup(UpdateEntryDialogLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(UpdateEntryDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(FirstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(9, Short.MAX_VALUE))
        );
        UpdateEntryDialogLayout.setVerticalGroup(
            UpdateEntryDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpdateEntryDialogLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(UpdateEntryDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(FirstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(UpdateEntryDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(LastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(UpdateEntryDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(BirthDayTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BirthMonthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BirthYearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(UpdateEntryDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(UpdateEntryDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(AddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(UpdateEntryDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(UpdateEntryDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UpdateButton)
                    .addComponent(jButton3))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        NumberTextField.addKeyListener(new KeyAdapter(){
            @Override
            public void keyPressed(KeyEvent ke){
                keyStrokeValidate(ke,NumberTextField,11);
            }
        });
        BirthMonthTextField.addKeyListener(new KeyAdapter(){
            @Override
            public void keyPressed(KeyEvent ke){
                keyStrokeValidate(ke,BirthMonthTextField,2);
            }
        });
        BirthYearTextField.addKeyListener(new KeyAdapter(){
            @Override
            public void keyPressed(KeyEvent ke){
                keyStrokeValidate(ke,BirthYearTextField,4);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 255));
        setMinimumSize(new java.awt.Dimension(450, 300));

        jTabbedPane1.setBackground(new java.awt.Color(255, 102, 204));
        jTabbedPane1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(268, 268));

        jScrollPane1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        for (int i =0; i<CRUD_Interface.firstNameList.size();i++){
            model.addElement(CRUD_Interface.bubbleSort(CRUD_Interface.firstNameList)[i]);
        }
        jList1.setBackground(new java.awt.Color(153, 255, 255));
        jList1.setModel(model);
        jList1.addListSelectionListener(new ListSelectionListener(){
            public void valueChanged(ListSelectionEvent listSelectionEvent){
                boolean adjust = listSelectionEvent.getValueIsAdjusting();
                System.out.println(", Adjusting? " + adjust);
                if (!adjust) {
                    JList list = (JList) listSelectionEvent.getSource();
                    int selections[] = list.getSelectedIndices();
                    Object selectionValues[] = list.getSelectedValues();
                    for (int i = 0, n = selections.length; i < n; i++) {
                        if (i == 0) {
                            System.out.println(" Selections: ");
                        }
                        System.out.println(selections[i] + "/" + selectionValues[i] + " ");
                        String[] Entry = CRUD_Interface.searchRow(selectionValues[i].toString(),CRUD_Interface.firstNameList);
                        LastNameOutput.setText(Entry[1]);
                        FirstNameOutput.setText(Entry[0]);
                        BirthdayOutput.setText(Entry[2]);
                        AddressOutput.setText(Entry[3]);
                        EmailOutput.setText(Entry[4]);
                        NumberOutput.setText(Entry[5]);
                    }
                }

            }
        });
        jScrollPane1.setViewportView(jList1);

        jTabbedPane1.addTab("Entries", jScrollPane1);

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setBackground(new java.awt.Color(255, 153, 153));
        jLabel1.setText("Last Name:");

        jLabel2.setBackground(new java.awt.Color(255, 153, 153));
        jLabel2.setText("First Name:");

        jLabel3.setBackground(new java.awt.Color(255, 153, 153));
        jLabel3.setText("Birthday:");

        jLabel4.setBackground(new java.awt.Color(255, 153, 153));
        jLabel4.setText("Number:");

        jLabel5.setBackground(new java.awt.Color(255, 153, 153));
        jLabel5.setText("Address:");

        jLabel6.setBackground(new java.awt.Color(255, 153, 153));
        jLabel6.setText("Email:");

        AddEntry.setBackground(new java.awt.Color(153, 255, 255));
        AddEntry.setText("Add New Entry");
        AddEntry.setToolTipText("");
        AddEntry.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        AddEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddEntryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(AddEntry, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LastNameOutput))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(FirstNameOutput))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BirthdayOutput))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EmailOutput))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(AddressOutput))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(NumberOutput)))
                        .addGap(0, 150, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(LastNameOutput))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(FirstNameOutput))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(BirthdayOutput))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(NumberOutput))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(AddressOutput))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(EmailOutput))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(AddEntry)
                .addContainerGap())
        );

        title.setText("Simbahan's Phonebook");

        UpdateEntry.setBackground(new java.awt.Color(255, 153, 153));
        UpdateEntry.setText("Update Info");
        UpdateEntry.setToolTipText("");
        UpdateEntry.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        UpdateEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateEntryActionPerformed(evt);
            }
        });

        DeleteEntry.setBackground(new java.awt.Color(102, 102, 255));
        DeleteEntry.setText("Delete Info");
        DeleteEntry.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        DeleteEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteEntryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(UpdateEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DeleteEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(UpdateEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DeleteEntry))))
                .addGap(120, 120, 120))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public static void keyStrokeValidate(KeyEvent ke,JTextField InputComponent, int CharCount){
        String field = InputComponent.getText();
        if ((( ke.getKeyChar() >= '0' && ke.getKeyChar() <= '9')&& field.length()  <= CharCount-1)
            ||(ke.getKeyChar() == '-')
            || ke.getKeyCode() == KeyEvent.VK_BACK_SPACE
            || ke.getKeyCode() == KeyEvent.VK_DELETE
            ){
            InputComponent.setEditable(true);
        } else{
            InputComponent.setEditable(false);
        }
    }
    private static boolean InputVerifier(String date,String Email,String number) {
        if (date.matches("^[0-9/]*$")&&Email.matches("^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+$")&&number.matches("^[0-9.-]*$")){
            System.out.println("Data Passes Regex Verification");
            return true;     
        } else{
            System.out.println("Data Did not Pass Regex Verification");
            return false;
        }
    }
    public static int indexLocate(DefaultListModel<String> model, String input){
            int i;
            for (i=0;i<model.size();i++){
                //for (int j = i+1;j<model.size();j++){
                    if(model.get(i).compareTo(input) > 0){
                        //System.out.println("<0 " + model.get(i).compareTo(input));
                        break;

                    }
                //}
            }
            return i;
        }
    public static String convertToTitleCaseIteratingChars(String text) {
    if (text == null || text.isEmpty()) {
        return text;
    }

    StringBuilder converted = new StringBuilder();

    boolean convertNext = true;
    for (char ch : text.toCharArray()) {
        if (Character.isSpaceChar(ch)) {
            convertNext = true;
        } else if (convertNext) {
            ch = Character.toTitleCase(ch);
            convertNext = false;
        } else {
            ch = Character.toLowerCase(ch);
        }
        converted.append(ch);
    }

    return converted.toString();
    }
    private void AddEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddEntryActionPerformed
        AddEntryDialog.setVisible(true);  
        
    }//GEN-LAST:event_AddEntryActionPerformed
    

    private void UpdateEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateEntryActionPerformed
        if(FirstNameOutput.getText().isEmpty()
            ||LastNameOutput.getText().isEmpty()
            ||AddressOutput.getText().isEmpty()
            ||BirthdayOutput.getText().isEmpty()
            || EmailOutput.getText().isEmpty()
            ||NumberOutput.getText().isEmpty()){
            
            System.out.println("Error: No Info to Update");
            JOptionPane.showMessageDialog(jPanel1,"Error: No Info to Update","Error",JOptionPane.ERROR_MESSAGE);
        }else{
            UpdateEntryDialog.setVisible(true);
            FirstNameTextField.setText(FirstNameOutput.getText());
            LastNameTextField.setText(LastNameOutput.getText());
            AddressTextField.setText(AddressOutput.getText());
            String[] DateSplices = BirthdayOutput.getText().split("/");
            BirthDayTextField.setText(DateSplices[0]);
            BirthMonthTextField.setText(DateSplices[1]);
            BirthYearTextField.setText(DateSplices[2]);
            EmailTextField.setText(EmailOutput.getText());
            NumberTextField.setText(NumberOutput.getText());
        }
        
        
    }//GEN-LAST:event_UpdateEntryActionPerformed
    private static void DeleteGUIChoice(DefaultListModel<String> model, String input ){
        try{
            int i;
            for (i=0;i<model.size();i++){
                    if(model.get(i).equals(input)){
                        model.remove(i);
                        System.out.println("GUI block removed");
                        break;
                    }
            }
        }catch(Exception err){
            System.out.println(err);
        }
        
    }
    private void DeleteEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteEntryActionPerformed
        // TODO add your handling code here:
        if(FirstNameOutput.getText().isEmpty()
            ||LastNameOutput.getText().isEmpty()
            ||AddressOutput.getText().isEmpty()
            ||BirthdayOutput.getText().isEmpty()
            || EmailOutput.getText().isEmpty()
            ||NumberOutput.getText().isEmpty()){
            
            System.out.println("Error: No Info to Delete");
            JOptionPane.showMessageDialog(jPanel1,"Error: No Info to Delete","Error",JOptionPane.ERROR_MESSAGE);
        }else{
            String[] choices= {"Yes","No"};
            int response=JOptionPane.showOptionDialog(this, "Do you confirm the Deletion of These Data?", "Deletion Confirmation", JOptionPane.INFORMATION_MESSAGE, JOptionPane.INFORMATION_MESSAGE, null, choices, choices[0]);
            switch (response) {
                case 0 -> {
                    CRUD_Interface.deleteRow(FirstNameOutput.getText(), EmailOutput.getText());
                    DeleteGUIChoice(model,FirstNameOutput.getText());
                    System.out.println("Data Deleted");
                    FirstNameOutput.setText("");
                    LastNameOutput.setText("");
                    AddressOutput.setText("");
                    BirthdayOutput.setText("");
                    EmailOutput.setText("");
                    NumberOutput.setText("");
                    CRUD_Interface.getAllRows();
                }
                case 1 -> System.out.println("Deletion cancelled");
                default -> System.out.println("No Choice");
            }
        }
    }//GEN-LAST:event_DeleteEntryActionPerformed

    private void BirthDayInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BirthDayInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BirthDayInputActionPerformed

    private void LastNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LastNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LastNameTextFieldActionPerformed

    private void FirstNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FirstNameTextFieldActionPerformed

    private void BirthDayTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BirthDayTextFieldActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_BirthDayTextFieldActionPerformed

    private void NumberTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumberTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumberTextFieldActionPerformed

    private void EmailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailTextFieldActionPerformed

    private void AddressTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddressTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddressTextFieldActionPerformed

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
        // TODO add your handling code here:
        String NewBirthDate = BirthDayTextField.getText()+"/"+BirthMonthTextField.getText()+"/"+BirthYearTextField.getText();
        if(InputVerifier(NewBirthDate, EmailTextField.getText(),NumberTextField.getText())){
            CRUD_Interface.updateRow(FirstNameOutput.getText(),CRUD_Interface.firstNameList, FirstNameTextField.getText());
            CRUD_Interface.updateRow(FirstNameOutput.getText(),CRUD_Interface.lastNameList, LastNameTextField.getText());
            CRUD_Interface.updateRow(FirstNameOutput.getText(),CRUD_Interface.BirthdayList, NewBirthDate);
            CRUD_Interface.updateRow(FirstNameOutput.getText(),CRUD_Interface.numberList, NumberTextField.getText());
            CRUD_Interface.updateRow(FirstNameOutput.getText(),CRUD_Interface.AddressList, AddressTextField.getText());
            CRUD_Interface.updateRow(FirstNameOutput.getText(),CRUD_Interface.EmailList, EmailTextField.getText());
            model.removeElement(FirstNameOutput.getText());
            model.add(indexLocate(model,   convertToTitleCaseIteratingChars(FirstNameTextField.getText())),FirstNameTextField.getText());
            FirstNameOutput.setText(FirstNameTextField.getText());
            LastNameOutput.setText(LastNameTextField.getText());
            BirthdayOutput.setText(NewBirthDate);
            NumberOutput.setText(NumberTextField.getText());
            AddressOutput.setText(AddressTextField.getText());
            EmailOutput.setText(EmailTextField.getText());
            UpdateEntryDialog.dispose();
            CRUD_Interface.getAllRows();
        }else{
            JOptionPane.showMessageDialog( UpdateEntryDialog,"Error: Incorrect Data","Error",JOptionPane.ERROR_MESSAGE);
            AddEntryDialog.dispose();
        }
        
    }//GEN-LAST:event_UpdateButtonActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        UpdateEntryDialog.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void AddEntryBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddEntryBackButtonActionPerformed
        // TODO add your handling code here:
        AddEntryDialog.dispose();
    }//GEN-LAST:event_AddEntryBackButtonActionPerformed

    private void SubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButtonActionPerformed
        // TODO add your handling code here:
        CRUD_Interface.getAllRows();
    }//GEN-LAST:event_SubmitButtonActionPerformed

    private void BirthMonthInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BirthMonthInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BirthMonthInputActionPerformed

    private void BirthYearInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BirthYearInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BirthYearInputActionPerformed

    private void BirthMonthTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BirthMonthTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BirthMonthTextFieldActionPerformed

    private void LastNameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LastNameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LastNameInputActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddEntry;
    private javax.swing.JButton AddEntryBackButton;
    private javax.swing.JDialog AddEntryDialog;
    private javax.swing.JTextField AddressInput;
    private javax.swing.JLabel AddressOutput;
    private javax.swing.JTextField AddressTextField;
    private javax.swing.JTextField BirthDayInput;
    private javax.swing.JTextField BirthDayTextField;
    private javax.swing.JTextField BirthMonthInput;
    private javax.swing.JTextField BirthMonthTextField;
    private javax.swing.JTextField BirthYearInput;
    private javax.swing.JTextField BirthYearTextField;
    private javax.swing.JLabel BirthdayOutput;
    private javax.swing.JButton DeleteEntry;
    private javax.swing.JTextField EmailInput;
    private javax.swing.JLabel EmailOutput;
    private javax.swing.JTextField EmailTextField;
    private javax.swing.JTextField FirstNameInput;
    private javax.swing.JLabel FirstNameOutput;
    private javax.swing.JTextField FirstNameTextField;
    private javax.swing.JTextField LastNameInput;
    private javax.swing.JLabel LastNameOutput;
    private javax.swing.JTextField LastNameTextField;
    private javax.swing.JTextField NumberInput;
    private javax.swing.JLabel NumberOutput;
    private javax.swing.JTextField NumberTextField;
    private javax.swing.JButton SubmitButton;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JButton UpdateEntry;
    private javax.swing.JDialog UpdateEntryDialog;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
